/**
 * System catalog types + adapters.
 *
 * The backend ``system_catalog.yaml`` (derived, generated by the astronomy
 * engine) merges ``stellar.yaml`` (stars / orbits / narrative bodies) with
 * ``planets.yaml`` (authoritative physical parameters + subsystems) into one
 * per-body catalog.  These adapters map catalog entries onto the existing
 * viewer types (StarData / PlanetData) so the 3D viewer consumes a single
 * source instead of merging — and deduplicating — two endpoints itself.
 */

import type { StarData } from '../viewers/StarMesh'
import type { PlanetData, OrbitalElementsData } from '../viewers/PlanetMesh'

export interface CatalogStar {
  id: string
  name?: string
  spectral_class?: string
  luminosity_class?: string
  position?: { x: number; y: number; z: number }
  luminosity_sol?: number
  mass_sol?: number
  radius_sol?: number
  temperature_k?: number
  age_gyr?: number
  ms_lifetime_gyr?: number
  evolution_progress?: number
  habitable_zone?: Record<string, number>
  habitable_zone_center_au?: number
}

export interface CatalogBodyDerived {
  tidally_locked?: boolean
  instellation_w_m2?: number
  instellation_earth_ratio?: number
  equilibrium_temperature_k?: number
  solar_day_days?: number | null
  days_per_year?: number
  in_conservative_habitable_zone?: boolean
}

export interface CatalogBody {
  id: string
  name?: string
  body_type?: string
  in_planets_yaml?: boolean
  parent_id?: string
  orbit?: {
    semi_major_axis_au?: number
    eccentricity?: number
    inclination_deg?: number
    period_days?: number
  }
  physical?: {
    mass_earth?: number
    radius_km?: number
    radius_earth?: number
    gravity_m_s2?: number
    rotation_period_days?: number
    axial_tilt_deg?: number
    albedo?: number
  }
  atmosphere?: {
    surface_pressure_atm?: number
    composition?: Record<string, number>
    greenhouse_factor?: number
  }
  hydrosphere?: { water_coverage?: number }
  lithosphere?: Record<string, unknown>
  magnetic_field_strength_ut?: number
  description?: Record<string, string>
  derived?: CatalogBodyDerived
}

export interface SystemCatalog {
  stars?: CatalogStar[]
  orbits?: OrbitalElementsData[]
  bodies?: CatalogBody[]
  target_body_id?: string
  warnings?: string[]
}

/** Map a catalog star entry to the 3D viewer's StarData shape. */
export function catalogStarToStarData(star: CatalogStar): StarData {
  return {
    id: star.id,
    name: star.name ?? star.id,
    spectral_class: star.spectral_class,
    luminosity_class: star.luminosity_class,
    position: star.position,
    luminosity: star.luminosity_sol,
    mass: star.mass_sol,
    radius: star.radius_sol,
    temperature: star.temperature_k,
  }
}

/** Map a catalog body entry (already merged, planets.yaml priority) to PlanetData. */
export function catalogBodyToPlanetData(body: CatalogBody): PlanetData {
  return {
    id: body.id,
    name: body.name ?? body.id,
    orbits: body.parent_id ?? '',
    planet_type: body.body_type,
    mass: body.physical?.mass_earth ?? 0,
    radius: body.physical?.radius_earth ?? 0,
    albedo: body.physical?.albedo,
    axial_tilt_deg: body.physical?.axial_tilt_deg,
    rotation_period_days: body.physical?.rotation_period_days,
    atmosphere: body.atmosphere ?? null,
    hydrosphere: body.hydrosphere ?? null,
  }
}
