#!/usr/bin/env python3
"""Generate the per-grid observed-climatology reference for the ΔT/ΔP layers.

The frontend's temperature-error / precipitation-error heatmaps previously diffed
each cell against a **zonal-mean** reference, which averages out longitude *and
elevation* (a 4844 m Tibetan cell always looked "~17 °C too cold").  This script
replaces that with a **per-grid** observed climatology — NCEP/NCAR Reanalysis-1
surface air temperature and GPCP v2.3 precipitation — bundled on their **native
grids**, which the frontend bilinearly samples at each cell's (lat, lon).

Each dataset keeps its own grid (they are offset by ~1.25° from each other):
resampling one onto the other's grid introduces a ~20% error in steep-gradient
regions like the Bangladesh monsoon coast (observed ≈ 2510 mm/yr read as 1966).
So the TS module carries two independent grids + a sampler parameterised by each.

Outputs ``frontend/src/viewers/map/spatialReference.ts``.  Regenerate whenever the
source climatology changes (rare — fixed Earth reference):

    uv run python scripts/earth/generate_spatial_reference.py \
        --temp private/tmp/climatology/ncep_air.mon.ltm.nc \
        --precip private/tmp/climatology/gpcp_precip.mon.mean.nc

Earth-only: a fictional world has no observed climatology to diff against.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import xarray as xr


def _fmt_ints(values: np.ndarray, per_line: int = 12) -> str:
    lines = []
    for i in range(0, len(values), per_line):
        lines.append("  " + ", ".join(str(int(v)) for v in values[i : i + per_line]) + ",")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--temp", required=True, help="NCEP air.mon.ltm.nc")
    parser.add_argument("--precip", required=True, help="GPCP precip.mon.mean.nc")
    parser.add_argument(
        "--output",
        default="frontend/src/viewers/map/spatialReference.ts",
        help="output TS module path",
    )
    args = parser.parse_args()

    # Temperature: NCEP air (°C), monthly climatology → annual mean, native grid
    # (lat 90 → −90 descending, lon 0 → 357.5).
    ncep = xr.open_dataset(args.temp, decode_times=False)
    air = ncep["air"]
    if air.attrs.get("units", "").lower().startswith("k"):
        air = air - 273.15
    t = air.mean(dim="time")
    t_lat = np.asarray(t.lat.values)  # 90 → −90
    t_lon = np.asarray(t.lon.values)  # 0 → 357.5
    temp = np.asarray(t.values)  # (nlat, nlon) lat-major, north→south

    # Precipitation: GPCP (mm/day), monthly → annual → mm/yr, native grid
    # (lat −88.75 → 88.75 ascending, lon 1.25 → 358.75).
    gpcp = xr.open_dataset(args.precip, decode_times=False)
    p = gpcp["precip"].mean(dim="time") * 365.25
    p_lat = np.asarray(p.lat.values)  # −88.75 → 88.75
    p_lon = np.asarray(p.lon.values)  # 1.25 → 358.75
    precip = np.asarray(p.values)  # (nlat, nlon) lat-major, south→north

    # Encode: temperature ×10 (int, 0.1 °C), precipitation int (mm/yr).
    temp_flat = np.rint(temp * 10).astype(np.int32).ravel()
    precip_flat = np.rint(precip).astype(np.int32).ravel()

    def grid_meta(lat: np.ndarray, lon: np.ndarray) -> str:
        dlat = float(lat[1] - lat[0])
        dlon = float(lon[1] - lon[0])
        return (
            f"{{ nlat: {len(lat)}, nlon: {len(lon)}, lat0: {float(lat[0])}, dlat: {dlat}, "
            f"lon0: {float(lon[0])}, dlon: {dlon} }}"
        )

    body = f"""/**
 * Earth per-grid observed climatology (native grids).
 *
 * Generated by ``scripts/earth/generate_spatial_reference.py`` from NCEP/NCAR
 * Reanalysis-1 surface air temperature (``air.mon.ltm.nc``) and GPCP v2.3
 * precipitation (``precip.mon.mean.nc``).  This is the per-grid reference for
 * the ΔT/ΔP error heatmaps — unlike the old zonal mean it carries the real
 * orography (Tibet ≈ −5.5 °C, not the +18 °C zonal mean) and land/ocean
 * contrast, so the deviation reflects the *model's* error, not elevation.
 *
 * The two datasets keep their native grids (offset ~1.25° from each other);
 * resampling one onto the other corrupts steep-gradient regions.  Each sampler
 * below is parameterised by its own grid metadata.
 *
 * Earth-only: a fictional world has no observed climatology to diff against.
 * Do not hand-edit; regenerate with the script.
 */

// temperature ×10 (0.1 °C), lat-major, north→south
export const OBS_TEMP_X10: number[] = [
{_fmt_ints(temp_flat)}
]

// precipitation (mm/yr), lat-major, south→north
export const OBS_PRECIP_MM: number[] = [
{_fmt_ints(precip_flat)}
]

export const OBS_TEMP_GRID = {grid_meta(t_lat, t_lon)}
export const OBS_PRECIP_GRID = {grid_meta(p_lat, p_lon)}

interface Grid {{
  nlat: number
  nlon: number
  lat0: number
  dlat: number
  lon0: number
  dlon: number
}}

/** Bilinear-sample the observed annual temperature (°C) at (lat, lon). */
export function observedTempAt(latDeg: number, lonDeg: number): number {{
  return _sample(latDeg, lonDeg, OBS_TEMP_X10, OBS_TEMP_GRID) / 10
}}

/** Bilinear-sample the observed annual precipitation (mm/yr) at (lat, lon). */
export function observedPrecipAt(latDeg: number, lonDeg: number): number {{
  return _sample(latDeg, lonDeg, OBS_PRECIP_MM, OBS_PRECIP_GRID)
}}

function _sample(latDeg: number, lonDeg: number, grid: number[], g: Grid): number {{
  // Grid row index in the array's native lat order (ascending or descending).
  const fi = (latDeg - g.lat0) / g.dlat
  let fj = ((lonDeg - g.lon0) / g.dlon) % g.nlon
  if (fj < 0) fj += g.nlon
  const i0 = Math.max(0, Math.min(g.nlat - 2, Math.floor(fi)))
  const j0 = Math.floor(fj)
  const j1 = (j0 + 1) % g.nlon
  const di = fi - i0
  const dj = fj - j0
  const v00 = grid[i0 * g.nlon + j0]
  const v01 = grid[i0 * g.nlon + j1]
  const v10 = grid[(i0 + 1) * g.nlon + j0]
  const v11 = grid[(i0 + 1) * g.nlon + j1]
  const top = v00 + (v01 - v00) * dj
  const bot = v10 + (v11 - v10) * dj
  return top + (bot - top) * di
}}
"""
    out = Path(args.output)
    out.write_text(body, encoding="utf-8")
    print(
        f"[OK] {out} ({out.stat().st_size / 1e3:.0f} KB) — "
        f"temp {float(temp.min()):.1f}..{float(temp.max()):.1f} °C on {len(t_lat)}×{len(t_lon)}, "
        f"precip {float(precip.min()):.0f}..{float(precip.max()):.0f} mm/yr on {len(p_lat)}×{len(p_lon)}"
    )


if __name__ == "__main__":
    main()
